In [17]:
import pandas as pd
# 读取csv文件
df = pd.read_csv(('C:\\Users\\dadada\\Desktop\\sunflower\\python_study\\homework\\hancheng.csv'))

In [18]:
df =  df[df.columns[:13]]

In [20]:
df = df.fillna(-99)

In [21]:
df = df.replace('缺失', -99)
df = df.replace(' ', -99)
df = df.replace('  ', -99)

In [22]:
## borthday convert to datetime
df['生日'] = pd.to_datetime(df['生日'])

In [23]:
df['年'] = df['生日'].dt.year
df['月'] = df['生日'].dt.month
df['日'] = df['生日'].dt.day

In [24]:
df['性别'] = df['性别'].map(lambda x: 1 if x == '男' else 0)

In [25]:
df['带镜左眼'].unique()

array([-99, '0.1', '0.8', '1', '0.4', '0.3', '0.6', '0.5', '0.25', '1.2'],
      dtype=object)

In [26]:
df['带镜右眼'] = df['带镜右眼'].astype('float')

In [27]:
df['带镜左眼'] = df['带镜左眼'].astype('float')

In [28]:
df['电脑验光右'] = pd.to_numeric(df['电脑验光右'], errors='coerce')

In [29]:
df['电脑验光左'] = pd.to_numeric(df['电脑验光左'], errors='coerce')

In [30]:
for i in df.columns[-5:-3]:
    df[i] = pd.to_numeric(i, errors='coerce')

In [31]:
df['年龄'] = pd.to_numeric(df['年龄'], errors='coerce')

In [34]:
df = df.drop(df[df['年龄']>100].index, axis = 0 )

In [37]:

df.to_csv('result.csv', index = False)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 0 to 1460
Data columns (total 16 columns):
school     1460 non-null object
姓名         1460 non-null object
性别         1460 non-null int64
生日         1460 non-null datetime64[ns]
年龄         1460 non-null int64
裸右         1460 non-null float64
裸左         1460 non-null float64
带镜右眼       1460 non-null float64
带镜左眼       1460 non-null float64
电脑验光右      1456 non-null float64
电脑验光左      1458 non-null float64
这一个戴镜时间    0 non-null float64
总戴镜时间      0 non-null float64
年          1460 non-null int64
月          1460 non-null int64
日          1460 non-null int64
dtypes: datetime64[ns](1), float64(8), int64(5), object(2)
memory usage: 193.9+ KB

In [39]:
df

,school,姓名,性别,生日,年龄,裸右,裸左,带镜右眼,带镜左眼,电脑验光右,电脑验光左,这一个戴镜时间,总戴镜时间,年,月,日
0,junior,张熙涵,1,2000-03-25 00:00:00.000000000,18,0.08,1.00,-99.0,-99.0,-99.000,-3.25,NaN,NaN,2000,3,25
1,junior,郭鑫,1,1999-12-22 00:00:00.000000000,18,0.20,0.10,0.5,0.1,-3.250,NaN,NaN,NaN,1999,12,22
2,junior,郭佳宝,1,1999-08-27 00:00:00.000000000,18,1.00,0.30,-99.0,-99.0,-99.000,0.00,NaN,NaN,1999,8,27
3,junior,丰妍玥,0,1999-12-13 00:00:00.000000000,18,0.30,0.40,-99.0,-99.0,2.250,-2.00,NaN,NaN,1999,12,13
4,junior,高康乐,1,2001-10-26 00:00:00.000000000,16,1.00,0.40,-99.0,-99.0,-99.000,-2.00,NaN,NaN,2001,10,26
5,junior,张宇洁,0,2000-09-21 00:00:00.000000000,17,0.20,0.12,0.8,0.8,-99.000,-99.00,NaN,NaN,2000,9,21
6,junior,孙雯楚,0,2000-05-28 00:00:00.000000000,18,0.30,0.15,1.0,1.0,-99.000,-99.00,NaN,NaN,2000,5,28
7,junior,张泽雨,0,2000-06-02 00:00:00.000000000,18,0.25,0.20,1.0,1.0,-99.000,-99.00,NaN,NaN,2000,6,2
8,junior,王元博,1,2000-01-24 00:00:00.000000000,18,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,2000,1,24
9,junior,曹泽会,1,2000-05-11 00:00:00.000000000,18,0.50,1.00,-99.0,-99.0,-1.000,-99.00,NaN,NaN,2000,5,11
10,junior,杨家乐,1,2000-02-13 00:00:00.000000000,18,0.40,0.20,-99.0,-99.0,-1.500,-2.00,NaN,NaN,2000,2,13
11,junior,乔世良,1,1999-12-14 00:00:00.000000000,18,0.15,0.14,0.8,0.4,-6.000,-5.50,NaN,NaN,1999,12,14
12,junior,雷卓,0,2000-04-19 00:00:00.000000000,18,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,2000,4,19
13,junior,李天玲,0,1999-11-20 00:00:00.000000000,18,0.60,1.00,-99.0,-99.0,-2.000,-99.00,NaN,NaN,1999,11,20
14,junior,王涛,1,1999-04-23 00:00:00.000000000,19,0.08,0.10,0.6,0.3,-10.375,-10.00,NaN,NaN,1999,4,23
15,junior,王伟,1,1999-12-18 00:00:00.000000000,18,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,1999,12,18
16,junior,高蕰,1,2000-10-12 00:00:00.000000000,17,0.12,0.12,0.8,0.8,-99.000,-99.00,NaN,NaN,2000,10,12
17,junior,高国强,1,2000-05-30 00:00:00.000000000,18,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,2000,5,30
18,junior,雷霄,0,1998-03-07 00:00:00.000000000,20,0.50,0.40,-99.0,-99.0,0.250,-0.25,NaN,NaN,1998,3,7
19,junior,马鑫,1,1999-06-27 00:00:00.000000000,19,0.15,0.12,1.0,1.0,-99.000,-99.00,NaN,NaN,1999,6,27
20,junior,吉泽阳,1,1999-09-23 00:00:00.000000000,18,0.25,0.30,1.0,1.0,-99.000,-99.00,NaN,NaN,1999,9,23
21,junior,高艺昭,0,1999-04-10 00:00:00.000000000,19,0.15,0.15,1.0,1.0,-99.000,-99.00,NaN,NaN,1999,4,10
22,junior,吴松哲,0,1999-10-15 00:00:00.000000000,18,0.15,0.12,1.0,1.0,-99.000,-99.00,NaN,NaN,1999,10,15
23,junior,李鹏,1,1998-12-23 00:00:00.000000000,19,0.40,0.50,-99.0,-99.0,-1.000,-1.00,NaN,NaN,1998,12,23
24,junior,年桂欣,0,1999-09-18 00:00:00.000000000,18,0.15,0.25,0.8,0.8,-99.000,-99.00,NaN,NaN,1999,9,18
25,junior,孙雪萌,0,2000-06-04 00:00:00.000000000,18,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,2000,6,4
26,junior,段泽锐,1,2001-01-23 00:00:00.000000000,17,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,2001,1,23
27,junior,丁豪楠,1,2001-09-18 00:00:00.000000000,16,0.40,0.50,1.0,1.0,-99.000,-99.00,NaN,NaN,2001,9,18
28,junior,王璐瑶,0,2001-08-03 00:00:00.000000000,16,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,2001,8,3
29,junior,孙婷,0,2001-04-23 00:00:00.000000000,17,0.25,0.25,1.0,1.0,-99.000,-99.00,NaN,NaN,2001,4,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,senior,樊亮琪,0,1996-04-11 00:00:00.000000000,22,0.25,0.20,0.6,1.0,-99.000,-99.00,NaN,NaN,1996,4,11
1432,senior,王爽迪,0,1996-04-01 00:00:00.000000000,22,0.12,0.15,1.0,1.0,-99.000,-99.00,NaN,NaN,1996,4,1
1433,senior,韩伟鹏,1,1996-11-19 00:00:00.000000000,21,0.30,0.30,1.0,1.0,-99.000,-99.00,NaN,NaN,1996,11,19
1434,senior,刘鑫琦,1,1996-11-23 00:00:00.000000000,21,0.50,0.40,-99.0,-99.0,-99.000,-99.00,NaN,NaN,1996,11,23
1435,senior,晋悦,0,1969-12-31 23:59:59.999999901,17,0.60,0.60,-99.0,-99.0,-1.250,-1.25,NaN,NaN,1969,12,31
1436,senior,晋欢,0,1969-12-31 23:59:59.999999901,17,0.20,0.12,-99.0,-99.0,-4.500,-4.75,NaN,NaN,1969,12,31
1437,senior,张璇,0,1969-12-31 23:59:59.999999901,16,1.00,0.60,-99.0,-99.0,-99.000,-1.25,NaN,NaN,1969,12,31
1438,senior,樊荣,0,1969-12-31 23:59:59.999999901,16,0.20,0.15,1.0,1.0,-99.000,-99.00,NaN,NaN,1969,12,31
1439,senior,张仙娟,0,1995-10-23 00:00:00.000000000,22,1.00,0.60,-99.0,-99.0,-99.000,-1.00,NaN,NaN,1995,10,23
1440,senior,尚欢,0,1995-12-20 00:00:00.000000000,22,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,1995,12,20
1441,senior,冯陈洁,0,1994-02-05 00:00:00.000000000,24,0.50,0.40,-99.0,-99.0,-5.000,-5.00,NaN,NaN,1994,2,5
1442,senior,晋希,0,1969-12-31 23:59:59.999999901,17,0.40,0.40,-99.0,-99.0,-4.000,-4.00,NaN,NaN,1969,12,31
1443,senior,贺竹颖,0,1969-12-31 23:59:59.999999901,15,0.20,0.40,-99.0,-99.0,-3.750,-4.00,NaN,NaN,1969,12,31
1444,senior,郝思蒙,0,1969-12-31 23:59:59.999999901,17,0.30,0.30,1.0,1.0,-99.000,-99.00,NaN,NaN,1969,12,31
1445,senior,刘梦羽,0,1969-12-31 23:59:59.999999901,16,0.20,0.20,0.6,0.6,-4.750,-4.25,NaN,NaN,1969,12,31
1446,senior,冀杨晨良,0,1969-12-31 23:59:59.999999901,16,0.15,0.60,1.0,1.0,-99.000,-99.00,NaN,NaN,1969,12,31
1447,senior,同夏利,0,1969-12-31 23:59:59.999999901,16,0.25,0.25,0.6,1.0,-99.000,-99.00,NaN,NaN,1969,12,31
1448,senior,陈佳珠,0,1969-12-31 23:59:59.999999901,18,0.30,0.25,1.0,0.8,-99.000,-99.00,NaN,NaN,1969,12,31
1449,senior,鱼幸子,0,1969-12-31 23:59:59.999999901,18,0.30,0.20,1.0,1.0,-99.000,-99.00,NaN,NaN,1969,12,31
1450,senior,党鈺婷,0,1969-12-31 23:59:59.999999901,18,0.25,0.40,1.0,1.0,-99.000,-99.00,NaN,NaN,1969,12,31
1451,senior,陈晨,0,1996-08-09 00:00:00.000000000,21,0.15,0.15,1.0,1.0,-99.000,-99.00,NaN,NaN,1996,8,9
1452,senior,吴嘉洁,0,1969-12-31 23:59:59.999999901,18,0.08,0.20,1.0,1.0,-99.000,-99.00,NaN,NaN,1969,12,31
1453,senior,高玉荣,0,1996-01-06 00:00:00.000000000,22,0.15,0.10,1.0,1.0,-99.000,-99.00,NaN,NaN,1996,1,6
1454,senior,马金萌,0,1999-03-06 00:00:00.000000000,19,0.10,0.20,1.0,1.0,-99.000,-99.00,NaN,NaN,1999,3,6
1455,senior,高琳,0,1969-12-31 23:59:59.999999901,18,0.25,0.30,-99.0,-99.0,-4.000,-4.00,NaN,NaN,1969,12,31
1456,senior,杨京,0,1969-12-31 23:59:59.999999901,18,1.00,1.00,-99.0,-99.0,-99.000,-99.00,NaN,NaN,1969,12,31
1457,senior,王洁,0,1995-10-15 00:00:00.000000000,22,0.40,0.40,1.0,1.0,-99.000,-99.00,NaN,NaN,1995,10,15
1458,senior,赵丹,0,1995-02-12 00:00:00.000000000,23,0.25,0.25,0.6,0.6,-6.000,-6.50,NaN,NaN,1995,2,12
1459,senior,元秦峰,1,1998-09-10 00:00:00.000000000,19,0.20,0.25,1.0,1.0,-99.000,-99.00,NaN,NaN,1998,9,10
1460,senior,刘华,1,1996-10-23 00:00:00.000000000,17,0.60,0.50,-99.0,-99.0,-1.500,-1.50,NaN,NaN,1996,10,23